[build]
  functions = "functions"
  publish = "public"

[dev]
  command = "npm start"

[[headers]]
  for = "/api/*"
  values = [
      { key = "Access-Control-Allow-Origin", value = "*" },
      { key = "Access-Control-Allow-Methods", value = "GET, POST, PUT, DELETE" },
      { key = "Access-Control-Allow-Headers", value = "Content-Type, Authorization"}
  ]