[build]
  functions = "functions"  # Directory containing your serverless functions
  publish = "public"       # Optional if you have static assets

[dev]
  command = "npm start"
  port = 3000              # The port your app runs on locally
