[build]
  functions = "functions"   # Ensure this matches the directory where your functions are

[dev]
  command = "npm start"
  port = 3000               # Ensure this matches your app's port

[functions]
  node_bundler = "esbuild"  # Optional: use esbuild for your serverless functions